### ISSUE TITLE
Gogoanime not working 

### ISSUE THREAD

**Issue by sbo2401** [justfoolingaround/animdl#107] opened 2022-02-15 15:42 UTC
Download and stream command not working for gogoanime

**Comment by justfoolingaround** [comment] 2022-02-15 16:12
Will work as intended so I guess I'll close this. Thanks for reporting though!

**Comment by sbo2401** [comment] 2022-02-15 16:13
Is it possible to select the video quality link mto grab

**Closed by justfoolingaround** 2022-02-15 16:12 UTC
