### ISSUE TITLE
IDM doesn't continue download after finish

### ISSUE THREAD

**Issue by ajam123** [justfoolingaround/animdl#29] opened 2021-07-08 19:33 UTC
I'm not sure if this supposed to be like this or no.

I have to manually stop it (CTRL+C) and it continues to the next episode.

**Comment by justfoolingaround** [comment] 2021-07-09 03:14
![](https://user-images.githubusercontent.com/79979949/125017940-d1d2ce80-e093-11eb-8c71-ca9d81113e3b.png)

It is supposed to be automatic and it seems to be working for me; let me know where you're running `animdl` at (the working directory.)

**Comment by shahrier-nafis** [comment] 2021-07-10 17:38
me having the same problem too ,some times this, some times this #28 , so its not helping as a batch downloader 😥

**Comment by shahrier-nafis** [comment] 2021-07-10 17:42
maybe grabing links as its downloading and use then later when needed

**Comment by justfoolingaround** [comment] 2021-07-10 17:55
Aight so a few points @shahrier-nafis 
- You're not having the same problem, the problem here is for undetected download files after downloading with IDM. Your problem occurs during grabbing due to an unstable internet connection.
- I can't solve the issues as long as it is irreproducible in my device, clearly your issue is related to an unstable internet connection; which is a rare case and a fix for that isn't applicable in anyway. (500 KBPS is NOT a high internet speed and even if it were, internet stability and internet speed are completely unrelated)
- Mate, if you're having such issues with this project as a batch downloader, I have bad news for you. This project is an optimized version of almost every standard batch downloader about there lmao.

And about grabbing during downloading, no. A rare case of internet instability won't make me implement an inefficient codebase.

**Comment by shahrier-nafis** [comment] 2021-07-10 19:06
no I'm saying this [I have to manually stop it (CTRL+C) and it continues to the next episode] also happened to me

**Comment by ajam123** [comment] 2021-07-11 07:54
Seems like it doesn't work since whenever it finished it changed to a random name with numbers instead of what it shows when being download.

Example:
When I was downloading it via IDM, it shows EP01 but after finish, it goes like d4ac4637b84f1c94a3c-01.

**Comment by justfoolingaround** [comment] 2021-07-11 07:55
Aight, can you drop the name of the anime name, episode and the provider?

**Comment by ajam123** [comment] 2021-07-11 11:43
JoJo no Kimyou na Bouken Ougon no Kaze - GGA.

It happened to all the episodes for me. Not sure if can be reproduce or not.

**Comment by justfoolingaround** [comment] 2021-07-11 12:01
It could be reproduced and is now fixed! Thanks for reporting this issue!

*This push has been sent to the unstable release and the stable one (pip installable package) will be updated to it soon!*

**Closed** 2021-07-11 12:01 UTC
