### ISSUE TITLE
How to use Crunchyroll Command?

### ISSUE THREAD

**Issue by NavDevP** [justfoolingaround/animdl#55] opened 2021-08-29 07:26 UTC
`animdl grab "crunchyroll:digimon-adventure-2020" -s 1 -e 1 -ll 0`

The response I got after this command.

`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): animepahe.com:443
DEBUG:urllib3.connectionpool:https://animepahe.com:443 "GET /api?q=crunchyroll%3Adigimon-adventure-2020&m=search HTTP/1.1" 200 None
[animdl-animepahe-searcher] Cannot find anything of that query.`

Why its searching animepahe even if I added Crunchyroll?

I think I am doing a mistake here?

**Comment by justfoolingaround** [comment] 2021-08-29 07:32
Update the repo using ```sh
py -m pip install git+https://github.com/justfoolingaround/animdl.git```

**Comment by NavDevP** [comment] 2021-08-29 07:39
Now it's giving

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by justfoolingaround** [comment] 2021-08-29 07:43
It isn't reproducible in my device, perhaps give it a retry?

![image](https://user-images.githubusercontent.com/79979949/131242683-f7075fec-9ec8-42c5-b9c0-3d4185dc23bc.png)

**Comment by NavDevP** [comment] 2021-08-29 07:52
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.13
A highly efficient anime downloader and streamer

Traceback (most recent call last):
  File "/usr/local/bin/animdl", line 10, in <module>
    sys.exit(__animdl_cli__())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 420, in internal
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/commands/grab.py", line 50, in animdl_grab
    session, query, logger, auto=auto, auto_index=index)
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/processors.py", line 66, in process_query
    return prompt_user(logger, searcher, provider)
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/processors.py", line 19, in prompt_user
    for n, anime in enumerate(anime_list_genexp, 1):
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/searcher.py", line 92, in search_crunchyroll
    content = json.loads(session.get(CRUNCHYROLL + "ajax/?req=RpcApiSearch_GetSearchCandidates").text.strip('*/\n -secur'))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This is the full error I'm getting. I don't know why mine is not working?

**Comment by NavDevP** [comment] 2021-08-29 09:00
Ok, actually it's working on windows but not on Debian.

Any reason why?

I can't figure it out.  :(

**Comment by ArjixWasTaken** [comment] 2021-08-29 22:57
Ok, according to the error it fails to parse some json data.
And that json data is the response from crunchyroll.
I don't really know why it fails to work in debian,
When opening the crunchyroll website (on Debian) does it work?
Do any anime play?

**Comment by justfoolingaround** [comment] 2021-09-01 19:21
HTTP Requests in Windows aren't any different from HTTP request on Debian.

If you're using a server, it may be rate-limited or blocked from accessing `.crunchyroll.com`.

_Note (if you're using Heroku): Crunchyroll has Heroku IPs blocked._

Since this issue is not related to `animdl` and there are no "fixes" to apply in the code. I'll close it for now.

**Closed by justfoolingaround** 2021-09-01 19:21 UTC
