### ISSUE TITLE
Unable to install animdl on Python 3.11 on Windows.

### ISSUE THREAD

**Issue by zezo357** [justfoolingaround/animdl#197] opened 2022-11-30 13:12 UTC
**Describe the bug**
I have python 3.10 and did try to install packages but it fails on setup.py

`pip install animdl`

![image](https://user-images.githubusercontent.com/25157308/204805214-35ac0d87-e732-4b6c-a85a-8ef68f1a3822.png)

**Comment by zezo357** [comment] 2022-11-30 13:20
pip install animdl==1.6.27 works

**Comment by Rashik4567** [comment] 2022-11-30 15:08
Same problem with my python 3.11 
pip install animdl==1.6.27 works fine

**Comment by AppleCanon** [comment] 2022-12-01 03:08
it installed fine for me, with 3.10.8, then again i do have a lot of python stuff installed. Have you tried doing "pip uninstall animdl" then trying again?

**Comment by zezo357** [comment] 2022-12-01 07:16
> it installed fine for me, with 3.10.8, then again i do have a lot of python stuff installed. Have you tried doing "pip uninstall animdl" then trying again?

It was a bug in the package and the owner fixed it

**Comment by Rashik4567** [comment] 2022-12-01 09:15
Still, theres some problem with lxml... I tried to install it standalone... but it fails. I tried on another machine(linux) and it works fine. But still on windows its broken ( I am suspecting some conflict with visual studio as Im not using a venv).

**Comment by rares9301** [comment] 2022-12-02 15:49
Im working on a fix for the lxml. Seems like the problem is on their end.

**Comment by rares9301** [comment] 2022-12-02 16:39
Seems like i had to downgrade to visual studio 2019 build tools ( you have 2022 installed ) 
also i installed a different whl for the lxml: lxml-4.9.0-cp311-cp311-win_amd64.whl ( get it from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml) )
download it and do pip install for it 
![image](https://user-images.githubusercontent.com/76567014/205341103-c177b7f5-7587-4565-97fb-62c6ed91d600.png)

Now all you have to do is to force your animdl to use the installed version of lxml instead of building wheels for the one that comes with.

**Comment by rares9301** [comment] 2022-12-02 17:06
I tested animdl and it works as expected. I didnt try it on VS 2022 cause i have no time rn to do a system restore. 
winver==11pro
python==3.11
MSBUILD==2019version
lxml==4.9.0 
custom installed from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml), entry lxml-4.9.0-cp311-cp311-win_amd64.whl
modified files : requirements.txt lxml==4.9.1 -> lxml==4.9.0 
![image](https://user-images.githubusercontent.com/76567014/205346302-d3961059-0c92-4086-a620-0e798005da99.png)
Use this as a workaround until 4.9.1 gets patched

**Comment by Rashik4567** [comment] 2022-12-02 21:20
> I tested animdl and it works as expected. I didnt try it on VS 2022 cause i have no time rn to do a system restore. 
> winver==11pro
> python==3.11
> MSBUILD==2019version
> lxml==4.9.0 
> custom installed from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml), entry lxml-4.9.0-cp311-cp311-win_amd64.whl
> modified files : requirements.txt lxml==4.9.1 -> lxml==4.9.0 
> ![image](https://user-images.githubusercontent.com/76567014/205346302-d3961059-0c92-4086-a620-0e798005da99.png)
> Use this as a workaround until 4.9.1 gets patched
> 

It works perfectly. Thank you.

**Comment by rares9301** [comment] 2022-12-02 23:58
> > I tested animdl and it works as expected. I didnt try it on VS 2022 cause i have no time rn to do a system restore. 
> > winver==11pro
> > python==3.11
> > MSBUILD==2019version
> > lxml==4.9.0 
> > custom installed from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml), entry lxml-4.9.0-cp311-cp311-win_amd64.whl
> > modified files : requirements.txt lxml==4.9.1 -> lxml==4.9.0 
> > ![image](https://user-images.githubusercontent.com/76567014/205346302-d3961059-0c92-4086-a620-0e798005da99.png)
> > Use this as a workaround until 4.9.1 gets patched
> > 
> 
> It works perfectly. Thank you.

are you on VS2022? cause i wanna roll back to it soon

**Comment by Rashik4567** [comment] 2022-12-03 06:24
> cause
Use a virtual environment (I used virtualenv). And use python -m with the env activated. It worked for me. It won't be installed globally, but at least it works.

**Comment by Rashik4567** [comment] 2022-12-03 06:24
> > > I tested animdl and it works as expected. I didnt try it on VS 2022 cause i have no time rn to do a system restore. 
> > > winver==11pro
> > > python==3.11
> > > MSBUILD==2019version
> > > lxml==4.9.0 
> > > custom installed from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml), entry lxml-4.9.0-cp311-cp311-win_amd64.whl
> > > modified files : requirements.txt lxml==4.9.1 -> lxml==4.9.0 
> > > ![image](https://user-images.githubusercontent.com/76567014/205346302-d3961059-0c92-4086-a620-0e798005da99.png)
> > > Use this as a workaround until 4.9.1 gets patched
> > > 
> > 
> > It works perfectly. Thank you.
> 
> are you on VS2022? cause i wanna roll back to it soon

Use a virtual environment (I used virtualenv). And use python -m with the env activated. It worked for me. It won't be installed globally, but at least it works.

**Comment by rares9301** [comment] 2022-12-03 09:01
Okay, i will come back later with the full resolution.

**Comment by Rashik4567** [comment] 2022-12-08 12:43
# To install it on windows 11, python 3.11 visual studio 2022 installed **(also works without vs2022)**. 
    - Setup a vritual environment. I have tested using virtualenv. `pip install virtualenv && virtualenv venv`.
    - Activate the environment. On powershell: `.\venv\Scripts\activate`. your environment should be activated. Now do everything inside the virtual env. 
![image](https://user-images.githubusercontent.com/58215479/206448519-d399b1c4-886a-4e5e-a29b-dffac6816fcc.png)

    - Download the lxml 4.9.0 from wheel. Here's an unofficial archives link.[lxml wheels]( https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml) .
    - Make sure you download the `lxml‑4.9.0‑cp311‑cp311‑win_****.whl` .
    - Install the wheel using pip install <filename: `lxml‑4.9.0‑cp311‑cp311‑win_****.whl`>
    - Clone or download and extract the animdl repository from github.
    - open the requirements.txt file and change lxml version from 4.9.1 to 4.9.0 
![image](https://user-images.githubusercontent.com/58215479/206447908-449c4fbc-50fa-45ce-89c3-09b3974633dc.png)

    - install animdl using command `pip install .` in the base directory of the repo.
    > it should install without any errors. if you encounter error, remove `lxml 4.9.x` from your requirements file.
    - You can now use animdl inside your virtualenv. Do not use this workaround on your global environment.

![image](https://user-images.githubusercontent.com/58215479/206448762-55a9cf4b-6ee1-41a5-85af-22db0f372031.png)

**Warning** This is a temporary workaround. Please update your packages as soon as this problem is fixed.

**Comment by justfoolingaround** [comment] 2022-12-18 04:29
As of `1.6.44`, this has been fixed by adding a custom package resolver that uses `lxml` builds from [Python Extension Packages for Windows](https://www.lfd.uci.edu/~gohlke/pythonlibs/). 

The `regex` package should also be fixed as of their latest versions.
![image](https://user-images.githubusercontent.com/79979949/208281519-df26510f-0fac-406b-b92d-3fe2b8df1428.png)

This custom package resolver is expected to be robust and usable if any such packages fail in newer versions of Python. This was added majorly because the only other option was to drop support for 3.11.

This is expected to be stable but Murphy's law states otherwise hence I'll keep this issue open for now. If anything fails in this system, be sure to inform me.

**Closed** 2022-12-24 13:45 UTC
Labels: bug: project error
